<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-E47PPVB" name="com.cashkaro.tests.forgotPassword.ForgotPasswordTest" tests="2" failures="1" timestamp="12 Feb 2016 09:36:44 GMT" time="38.152" errors="0">
  <testcase name="verifyForgotPasswordTest" time="34.472" classname="com.cashkaro.tests.forgotPassword.ForgotPasswordTest"/>
  <testcase name="verifyForgotPasswordErrorTest" time="3.680" classname="com.cashkaro.tests.forgotPassword.ForgotPasswordTest">
    <failure type="java.lang.AssertionError" message="Error message is not displayed expected [Please enter a valid email.] but found [Please enter valid email address.]">
      <![CDATA[java.lang.AssertionError: Error message is not displayed expected [Please enter a valid email.] but found [Please enter valid email address.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.cashkaro.helpers.ForgotPasswordHelper.verifyForgotPasswordError(ForgotPasswordHelper.java:52)
	at com.cashkaro.tests.forgotPassword.ForgotPasswordTest.verifyForgotPasswordErrorTest(ForgotPasswordTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- verifyForgotPasswordErrorTest -->
</testsuite> <!-- com.cashkaro.tests.forgotPassword.ForgotPasswordTest -->
